recipes/urls.py
from django.urls import path

from recipes.views import (
    RecipeListView,
    RecipeDetailView,
    RecipeCreateView,
    RecipeUpdateView,
    RecipeDeleteView,
    log_rating,
)

urlpatterns = [
    path("", RecipeListView.as_view(), name="recipes_list"),
    path("<int:pk>/", RecipeDetailView.as_view(), name="recipe_detail"),
    path("new/", RecipeCreateView.as_view(), name="recipe_new"),
    path("<int:pk>/edit", RecipeUpdateView.as_view(), name="recipe_edit"),
    path("<int:recipe_id>/ratings/", log_rating, name="recipe_rating"),
    path("<int:pk>/delete/", RecipeDeleteView.as_view(), name="recipe_delete"),
]

scrumptious/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path, reverse_lazy
from django.views.generic.base import RedirectView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("recipes/", include("recipes.urls")),
    path("tags/", include("tags.urls")),
    path("accounts/login/", auth_views.LoginView.as_view(), name="login"),
    path("accounts/logout/", auth_views.LogoutView.as_view(), name="logout"),
    path(
        "",
        RedirectView.as_view(url=reverse_lazy("recipes_list")),
        name="home",
    ),
]

tags/urls.py
from django.urls import path

from tags.views import (
    TagListView,
    TagDetailView,
)

urlpatterns = [
    path("", TagListView.as_view(), name="tags_list"),
    path("<int:pk>/", TagDetailView.as_view, name="tag_detail"),
]

recipes/models.py
from django.db import models
from django.conf import settings
from django.core.validators import MaxValueValidator, MinValueValidator

USER_MODEL = settings.AUTH_USER_MODEL

# Create your models here.
class Recipe(models.Model):
    name = models.CharField(max_length=125)
    author = models.ForeignKey(
        USER_MODEL, related_name="recipes", on_delete=models.CASCADE, null=True
    )
    description = models.TextField()
    image = models.URLField(null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    content = models.TextField()
    updated = models.DateTimeField(auto_now=True)
    origin = models.TextField

    def __str__(self):
        return self.name


class Step(models.Model):
    order = models.SmallIntegerField()
    directions = models.TextField()
    author = models.ForeignKey(
        "Recipe", related_name="steps", on_delete=models.PROTECT
    )
    food_items = models.ManyToManyField("FoodItem", blank=True)

    def __str__(self):
        return self.order


class Measure(models.Model):
    name = models.CharField(max_length=30, unique=True)
    abbreviation = models.CharField(max_length=10, unique=True)

    def __str__(self):
        return self.name


class FoodItem(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Ingredient(models.Model):
    amount = models.FloatField
    recipe = models.ForeignKey(
        "Recipe",
        related_name="ingredients",
        on_delete=models.CASCADE,
    )
    measure = models.ForeignKey(
        "Measure",
        on_delete=models.PROTECT,
    )
    food = models.ForeignKey("FoodItem", on_delete=models.PROTECT)

    def __str__(self):
        amount = str(self.amount)
        measure = self.measure.name
        food = self.food.name
        return amount + " " + measure + " " + food


class Rating(models.Model):
    value = models.PositiveSmallIntegerField(
        validators=[
            MaxValueValidator(5),
            MinValueValidator(1),
        ]
    )
    recipe = models.ForeignKey(
        "Recipe",
        related_name="ratings",
        on_delete=models.CASCADE,
    )

tags/models.py
from django.db import models


# Create your models here.


class Tag(models.Model):
    name = models.CharField(max_length=20)
    recipes = models.ManyToManyField("recipes.Recipe", related_name="tags")

    def __str__(self):
        return self.name

recipes/forms.py
from django import forms


from recipes.models import Rating


class RatingForm(forms.ModelForm):
    class Meta:
        model = Rating
        fields = ["value"]

recipes/views.py
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin

from recipes.forms import RatingForm
from recipes.models import Recipe


# def create_recipe(request):
#     if request.method == "POST" and RecipeForm:
#         form = RecipeForm(request.POST)
#         if form.is_valid():
#             recipe = form.save()
#             return redirect("recipe_detail", pk=recipe.pk)
#     elif RecipeForm:
#         form = RecipeForm()
#     else:
#         form = None
#     context = {
#         "form": form,
#     }
#     return render(request, "recipes/new.html", context)


class RecipeCreateView(LoginRequiredMixin, CreateView):
    model = Recipe
    fields = ["name", "description", "image"]
    template_name = "recipes/new.html"
    success_url = reverse_lazy("recipes_list")

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class RecipeUpdateView(LoginRequiredMixin, UpdateView):
    model = Recipe
    fields = ["name", "author", "description", "image"]
    template_name = "recipes/edit.html"
    success_url = reverse_lazy("recipes_list")


# def change_recipe(request, pk):
#     if Recipe and RecipeForm:
#         instance = Recipe.objects.get(pk=pk)
#         if request.method == "POST":
#             form = RecipeForm(request.POST, instance=instance)
#             if form.is_valid():
#                 form.save()
#                 return redirect("recipe_detail", pk=pk)
#         else:
#             form = RecipeForm(instance=instance)
#     else:
#         form = None
#     context = {
#         "form": form,
#     }
#     return render(request, "recipes/edit.html", context)


class RecipeListView(ListView):
    model = Recipe
    context_object_name = "recipes"
    template_name = "recipes/list.html"
    paginate_by = 2

    def get_queryset(self):
        querystring = self.request.GET.get("q")
        if querystring is None:
            querystring = ""
        return Recipe.objects.filter(description__icontains=querystring)


# def show_recipes(request):
#     context = {
#         "recipes": Recipe.objects.all() if Recipe else [],
#     }
#     return render(request, "recipes/list.html", context)


# def show_recipe(request, pk):
#     context = {
#         "recipe": Recipe.objects.get(pk=pk) if Recipe else None,
#     }
#     return render(request, "recipes/detail.html", context)


class RecipeDetailView(DetailView):
    model = Recipe
    context_object_name = "recipe"
    template_name = "recipes/detail.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["rating_form"] = RatingForm()
        return context


def log_rating(request, recipe_id):
    if request.method == "POST":
        form = RatingForm(request.POST)
        try:
            if form.is_valid():
                rating = form.save(commit=False)
                rating.recipe = Recipe.objects.get(pk=recipe_id)
                rating.save()
        except Recipe.DoesNotExist:
            return redirect("recipes_list")
    return redirect("recipe_detail", pk=recipe_id)


class RecipeDeleteView(LoginRequiredMixin, DeleteView):
    model = Recipe
    template_name = "recipes/delete.html"
    success_url = reverse_lazy("recipes_list")

tags/views.py
from django.shortcuts import render, redirect
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView


from tags.models import Tag


# Create your views here.
# def show_tags(request):
#     context = {
#         "tags": Tag.objects.all() if Tag else None,
#     }
#     return render(request, "tags/list.html", context)


class TagListView(ListView):
    model = Tag
    template_name = "tags/list.html"


class TagDetailView(DetailView):
    model = Tag
    template_name = "tags/detail.html"

recipes/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>New Recipe - Scrumptious</title>
        <link rel="stylesheet" href="{% static 'css/app.css' %}">
    </head>
    <body>
        <header>
            <nav>
                <ul>
                    <li>
                        <a href="{% url 'home' %}">Scrumptious</a>
                    </li>
                    {% if user.is_staff %}
                        <li>
                            <a href="{% url 'admin:index' %}">Admin</a>
                        </li>
                    {% endif %}
                    <li>
                        <a href="{% url 'recipe_new' %}">Write a recipe</a>
                    </li>
                    {% if user.is_authenticated %}
                        <li>
                            <a href="{% url 'logout' %}">Logout</a>
                        </li>
                    {% endif %}
                </ul>
            </nav>
            {% block pagination %}
            {% endblock pagination %}
        </header>
        {% block content %}
        {% endblock content %}
    </body>
</html>

recipes/templates/recipes/delete.html
{% extends 'base.html' %}
{% block content %}
    <main>
        <form method="post">
            {% csrf_token %}
            <p>Are you sure you want to delete "{{ recipe }}"?</p>
            {{ form.as_p }}
            <div class="control">
                <button class="button">Delete</button>
            </div>
        </form>
    </main>
{% endblock content %}

recipes/templates/recipes/detail.html
{% extends 'base.html' %}
{% load markdownify %}
{% block content %}
    <main class="recipe-detail">
        <div>
            <a href="{% url 'recipe_edit' recipe.id %}">Edit</a>
            <a href="{% url 'recipe_delete' recipe.id %}">Delete</a>
        </div>
        {% if recipe.image %}<img src="{{ recipe.image }}" class="pull-right">{% endif %}
        <h1>{{ recipe.name }}</h1>
        <h2>by: {{ recipe.author | default_if_none:"Unknown" }}</h2>
        <p>
            Created on {{ recipe.created }} |
            Updated on {{ recipe.updated }}
        </p>
        <form method="post" action="{% url 'recipe_rating' recipe.id %}">
            {% csrf_token %}
            {{ rating_form.as_p }}
            <button class="button">Rate</button>
        </form>
        <p>
            Tags:
            {% for tag in recipe.tags.all %}{{ tag.name }}{% endfor %}
        </p>
        {{ recipe.description | markdownify }}
        <h2>Ingredients</h2>
        <table>
            <thead>
                <tr>
                    <th colspan="2">Amount</th>
                    <th>Food item</th>
                </tr>
            </thead>
            <tbody>
                {% for ingredient in recipe.ingredients.all %}
                    <tr>
                        <td>{{ ingredient.amount }}</td>
                        <td>{{ ingredient.measure.name }}</td>
                        <td>{{ ingredient.food.name }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        <h2>Steps</h2>
        <ol>
            {% for step in recipe.steps.all %}<li>{{ step.directions }}</li>{% endfor %}
        </ol>
        <p>
            <a href="{% url "recipe_edit" recipe.id %}">Edit Recipe</a>
        </p>
    </main>
{% endblock content %}

recipes/templates/recipes/edit.html
{% extends 'base.html' %}
{% block content %}
    <main class="recipe-form">
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <div class="control">
                <button class="button">Update</button>
            </div>
        </form>
    </main>
{% endblock content %}

recipes/templates/recipes/list.html
{% extends 'base.html' %}
{% block content %}
    <main class="recipe-grid">
        {% for recipe in recipes %}
            <div class="recipe-card">
                <h2 class="recipe-card-title">
                    <a href="{% url 'recipe_detail' recipe.pk %}">{{ recipe.name }}</a>
                </h2>
                <p class="recipe-card-date">{{ recipe.updated }}</p>
            </div>
        {% endfor %}
    </main>
{% endblock content %}

recipes/templates/recipes/new.html
{% extends 'base.html' %}
{% block content %}
    <main class="recipe-form">
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <div class="control">
                <button class="button">Create</button>
            </div>
        </form>
    </main>
{% endblock content %}

tags/templates/tags/list.html
{% extends 'base.html' %}
{% block pagination %}
    <div class="pagination">
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a href="?page=1">&laquo; first</a>
                <a href="?page={{ page_obj.previous_page_number }}">previous</a>
            {% endif %}
            <span class="current">Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.</span>
            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">next</a>
                <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
    </div>
{% endblock pagination %}
{% block content %}
    <main class="recipe-grid">
        {% for tag in tag_list %}
            <div class="recipe-card">
                <h2 class="recipe-card-title">
                    <a href="{% url 'tag_detail' tag.id %}">{{ tag.name }}</a>
                </h2>
                {% for recipe in tag.recipes.all %}
                    <p>
                        <a href="{% url 'recipe_detail' recipe.pk %}">{{ recipe.name }}</a>
                    </p>
                {% endfor %}
            </div>
        {% empty %}
            <div>
                <h1>No tags, yet</h1>
                <p>
                    Would you like to
                    <a href="{% url 'tag_new' %}">create</a>
                    one?
                </p>
            </div>
        {% endfor %}
    </main>
{% endblock content %}